services:
  - type: web
    name: deckdev-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: deckdev-db
          property: connectionString

databases:
  - name: deckdev-db
    databaseName: deckdev
    user: deckdev_user
    plan: free
